# Reference: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
reporting: "off"
startuppopupversion: 1
gui:
  scrollHeight: 3
  scrollPastBottom: false
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta --tabs 2 --paging=never --24-bit-color=never --theme="OneHalfDark"
      --commit-style=box --commit-color=247
      --file-style=box --file-color=12 --hunk-color=12
      --plus-color=22 --plus-emph-color=28
      --minus-color=52 --minus-emph-color=88
      --keep-plus-minus-markers
    autoFetch: false
