# Reference: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
reporting: "off"
startuppopupversion: 1
gui:
  scrollHeight: 3
  scrollPastBottom: false
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: always
    pager: delta
      --paging=never
      --24-bit-color=never
      --features "256color decorations line-numbers navigate"
    autoFetch: false
